version: '3.8'
services:
    php:
        container_name: covid-apache
        build:
            context: ./docker
            dockerfile: covid_app.Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes :
            - ./databases/schema/covid_app.sql:/docker-entrypoint-initdb.d/covid_app.sql
        ports:
            - "9906:3306"
    phpmyadmin:
        container_name : phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
    composer:
        container_name : composer
        image: composer:latest
        volumes:
            - ./:/var/www/html/